{
  "name": "go test",
  "on":   ["push"],
  "jobs": {
    "test": {
      "strategy": {
        "matrix": {
          "go-version": ["1.18.x", "1.22.x"],
          "os":         ["ubuntu-latest", "macos-latest", "windows-latest"]
        }
      },
      "runs-on": "${{ matrix.os }}",
      "steps": [
        {
          "uses": "actions/setup-go@v5",
          "with": {"go-version": "${{ matrix.go-version }}"}
        },
        {
          "uses": "actions/checkout@v4"
        },
        {
          "run": "go test -v ./..."
        },
        {
          "run": "go install -v ./cmd/toml-test"
        }
      ]
    }
  }
}
